# sfda_rsd/connectors/error_codes.py
"""SFDA DTTS Error Code descriptions (English).

Sourced from ErrorCodeListService. Used to show user-friendly messages
in transaction logs and UI alerts.
"""

SFDA_ERROR_CODES = {
    "00000": "Success",
    "10201": "Success",
    "10215": "Success (no description)",
    "10216": "Success (no description)",
    "10306": "Product is registered for another manufacturer.",
    "10307": "Product is registered for another warehouse.",
    "10308": "Product is already registered for another pharmacy.",
    "10309": "Product is already registered in another hospital.",
    "10600": "GTIN must be 14 characters.",
    "10601": "Batch Number must be 2 to 20 characters.",
    "10602": "Serial Number must be 2 to 20 characters.",
    "10603": "Drug was not recalled before. Recall first, then cancel.",
    "11002": "SFDA database error.",
    "11010": "Please fill the missing information.",
    "11013": "Product barcode (GTIN) is missing or invalid.",
    "11015": "Production date is missing or incorrect.",
    "11016": "Expiry date (XD) is missing or incorrect.",
    "11017": "Serial number information is missing.",
    "11018": "Sender GLN (FROMGLN) is missing or invalid.",
    "11019": "Receiver GLN (TOGLN) is missing or invalid.",
    "11020": "PRODUCT information is not entered in PRODUCTLIST.",
    "11023": "You do not have permission to use this service.",
    "11026": "Prescription Number must be defined.",
    "11027": "Prescription number already registered.",
    "11028": "EID information is missing or invalid.",
    "11029": "PID information is missing or invalid.",
    "11030": "No sale performed for the indicated prescription number.",
    "11031": "XML structure is not compatible with WSDL.",
    "11033": "If receiver is reimbursement agency, product list must be empty.",
    "11035": "Product/GTIN not found or not registered in SFDA system.",
    "11036": "Product/Serial not found in your inventory for this operation.",
    "11038": "Expiry date cannot exceed production date by more than 7 years.",
    "11039": "First 13 characters of username must match your GLN.",
    "11040": "PRODUCT information has not been entered in PRODUCTS.",
    "11042": "Insufficient active quantity for dispatch. Check drug count.",
    "11043": "Quantity exceeds the quantity shipped.",
    "11045": "Indicated batch number has been recalled.",
    "11801": "Undefined product level.",
    "11802": "Invalid serial number.",
    "11803": "Invalid recall operation level.",
    "11804": "Invalid block operation level.",
    "11805": "No action has been taken on this product.",
    "11806": "Prescription number required for prescription drugs.",
    "11807": "Destination stakeholder cannot receive this drug.",
    "11808": "Cannot cancel supply for imported products.",
    "11809": "Cannot cancel import for produced products.",
    "11810": "Stakeholder not authorized for human drugs.",
    "11811": "Stakeholder not authorized for veterinary drugs.",
    "11812": "GTIN + BN has been recalled. Cannot produce these products.",
    "11813": "Export prohibited to the selected country.",
    "11814": "Sender user is passive. Cannot perform this operation.",
    "11815": "Destination stakeholder must be different from sender.",
    "11816": "Receiver stakeholder is passive.",
    "11817": "Explanation field cannot be empty.",
    "11818": "Use deactivation notification for expired units.",
    "11819": "Dispatch notification not found for the given notification ID.",
    "11902": "Receiver is not registered in the system.",
    "11903": "Undefined seller stakeholder.",
    "11904": "Receiver stakeholder is not active.",
    "11905": "Seller stakeholder is not active.",
    "20001": "Source GLN (FROMGLN) information is missing.",
    "20002": "Target GLN (TOGLN) information is missing.",
    "20005": "File not found in service attachment.",
    "20006": "Cannot send more than one file.",
    "20007": "File format is not supported.",
    "20008": "Transport ID not found in the system.",
    "20009": "Maximum file size is 10 MB.",
    "20010": "Image size exceeds the allowed limit.",
    "20101": "Use 'Provide not received transfer' option for sent packages.",
    "20201": "Invalid stakeholder type.",
    "20222": "Request contains both valid and invalid elements.",
    "21000": "Prescription date is invalid.",
    "21002": "Receiver GLN format is incorrect. Must be 13 digits.",
    "21003": "Unsupported package format. Must be ZIP.",
    "21004": "Maximum package size is 10 MB.",
    "21005": "You can send only one package at a time.",
    "21006": "Transport ID not found in the system.",
    "21008": "Stakeholder cannot be found in the system.",
    "21009": "Stakeholder you are sending to is deactivated.",
    "21010": "Package to receive not found in the system.",
    "21011": "Package cannot be sent to its original owner.",
    "21012": "Package receive attempt limit exceeded.",
    "21013": "Sender GLN format is incorrect. Must be 13 digits.",
    "21014": "You cannot get info on packages where you are not sender/receiver.",
    "21015": "Start date cannot be later than end date.",
    "21017": "Stakeholder is not authorized for this operation.",
    "21018": "Status matrix definition missing. Contact system admin.",
    "21019": "Undefined reason.",
    "21020": "Invalid deactivation reason.",
    "21021": "Invalid target GLN.",
    "21022": "This drug can be sold only to hospitals.",
    "21023": "Cannot cancel operation related to another stakeholder.",
    "21024": "This drug can only be supplied by importing.",
    "21025": "This drug can only be supplied by manufacturing, not importing.",
    "21026": "Invalid user.",
    "21027": "One of fromGLN or toGLN must be entered.",
    "21030": "Account not subscribed. Check subscription status.",
    "21031": "Insufficient balance in subscription package.",
    "40001": "Product is not registered for you.",
    "40002": "Product is not in your inventory.",
    "40003": "Product is not in your inventory.",
    "40005": "Product has been recalled.",
    "40006": "Product has expired.",
    "40007": "A product in your inventory has been recalled.",
    "40008": "Product has been recalled by another stakeholder.",
    "40009": "Product registered on you has been recalled at another level.",
    "50000": "SFDA system error. Contact system administrator.",
    "50004": "Cannot receive notification ID.",
    "50005": "IP not logged.",
    "60000": "Product has already been deactivated.",
    "60005": "Product has been exported.",
    "60006": "Product has been consumed.",
    "60007": "Product has been recalled.",
    "60009": "This dispatch has already been accepted previously.",
    "60022": "Product has been suspended.",
    "80000": "Incorrect username or password.",
    "80001": "Username is empty.",
    "80002": "Password is empty.",
    "80004": "User temporarily blocked. Try again later.",
    "80005": "Account is not active. Contact system administrator.",
    "80100": "Database error.",
    "80199": "Stakeholder user with specified username not found.",
    "80200": "Stakeholder not found.",
    "80201": "Invalid stakeholder type.",
    "80202": "Invalid GLN format.",
    "80506": "Product not found.",
    "80508": "Uncompleted operation in progress. Wait for it to finish.",
    "80509": "Operation already performed. Wait 5 minutes.",
    "80609": "Serial numbers exceed 200,000 per request limit.",
    "80610": "Products exceed 100,000 per request limit.",
    "98765": "Input error. Request cannot be processed.",
    "99000": "No block operation associated with this notification ID.",
    "99001": "Block cancel operation unsuccessful.",
    "99002": "Block operation already cancelled.",
    "99003": "Block operation has been recalled. Cannot cancel.",
    "99101": "Block recall operation unsuccessful.",
    "99103": "Block operation already recalled.",
    "99111": "GTIN/BN has been blocked. Perform recall in Block Screen first.",
}


def get_error_description(rc_code):
    """Get user-friendly error description for an SFDA RC code."""
    if not rc_code:
        return "Unknown error (empty response code)"
    return SFDA_ERROR_CODES.get(str(rc_code), f"Unknown SFDA error (RC: {rc_code})")
